Repository chingu-voyages/moonshot-chingu-quiz, pull requests merged in 2020-10, with the labels that each got.

#36 Feature/quiz selection
  .eslintrc.js
  client/components/quizTiles/QuizTile.js
  client/components/quizTiles/styles.js
  client/components/shared/styles.js
  client/pages/index.js
  client/pages/quizzes.js
  client/public/CSS3_Logo_200.png
  package.json
Labels: feature

#42 #30 adjust header to fit design
  client/components/header/Header.js
  client/components/header/MobileMenu.js
  client/components/header/styles.js
Labels: Hacktober

#43 ESLint config modifications - env setups and react/jsx-props-no-spreading
  .eslintrc.js
  client/components/header/Header.js
  client/pages/index.js
  client/pages/quizzes.js
  server/package-lock.json
Labels: Hacktober

#53 Feature/quiz api routes
  .eslintrc.js
  client/components/header/Header.js
  client/pages/index.js
  client/pages/quizzes.js
  server/exampleDB.sql
  server/quiz_examples/javascript_quiz.json
  server/routes/apiV1/quiz/get.js
  server/routes/apiV1/quiz/index.js
  server/routes/apiV1/quiz/post.js
Labels: feature, hacktoberfest-accepted

#55 Feature/quiz selection
  .eslintrc.js
  client/components/header/Header.js
  client/components/header/MobileMenu.js
  client/components/header/styles.js
  client/components/quizSelection/QuizTile.js
  client/components/quizSelection/TopicSelection.js
  client/components/quizSelection/styles.js
  client/components/quizTiles/QuizTile.js
  client/components/shared/styles.js
  client/pages/quizzes.js
  package-lock.json
  package.json
  server/.env.example
  server/.gitignore
  server/db/config.js
  server/index.js
  server/package-lock.json
  server/package.json
Labels: feature, hacktoberfest-accepted

#51 #33 add hero section
  client/components/frontpage/HeroSection.js
  client/pages/index.js
Labels: hacktoberfest-accepted

#52 dev startup and setup scripts
  package-lock.json
  package.json
Labels: hacktoberfest-accepted, setup

#62 #33 add info section
  client/components/frontpage/InfoSection.js
  client/pages/index.js
Labels: hacktoberfest-accepted

#39 Documentation Setup
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#64 Setup/#50 set up themeprovider
  client/components/frontpage/HeroSection.js
  client/components/frontpage/InfoSection.js
  client/components/header/styles.js
  client/pages/_app.js
Labels: hacktoberfest-accepted

#68 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest-accepted

#69 add a PR template
  .github/ISSUE_TEMPLATE/pull-request-template.md
Labels: hacktoberfest-accepted

#54 Feature/quiz api routes
  server/controllers/apiV1/answer/get.js
  server/controllers/apiV1/answer/index.js
  server/controllers/apiV1/quiz/get.js
  server/controllers/apiV1/quiz/index.js
  server/controllers/apiV1/quiz/post.js
  server/db/config.js
  server/db/index.js
  server/db/queries/answer/index.js
  server/db/queries/answer/insert.js
  server/db/queries/answer/select.js
  server/db/queries/question/index.js
  server/db/queries/question/insert.js
  server/db/queries/question/select.js
  server/db/queries/quiz/index.js
  server/db/queries/quiz/insert.js
  server/db/queries/quiz/select.js
  server/exampleDB.sql
  server/index.js
  server/package-lock.json
  server/package.json
  server/quiz_examples/javascript_quiz.json
  server/routes/apiV1/answer.js
  server/routes/apiV1/index.js
  server/routes/apiV1/quiz.js
Labels: feature, hacktoberfest-accepted

#71 fix file structure of templates
  .github/PULL_REQUEST_TEMPLATE/pull-request-template.md
Labels: Improvement

#77 fixing PR template for good
  .github/pull-request-template.md
Labels: Improvement

#56 Feature/quiz selection
  client/api-routes.js
  client/components/header/styles.js
  client/components/quizSelection/QuizTile.js
  client/components/quizSelection/TopicSelection.js
  client/components/quizSelection/TopicSelectionChoice.js
  client/components/quizSelection/styles.js
  client/components/shared/DisplayMessage.js
  client/components/shared/styles.js
  client/package-lock.json
  client/package.json
  client/pages/dummy-quiz-data.js
  client/pages/quizzes.js
  client/styles/globals.css
  server/.env.example
  server/exampleDB.sql
Labels: feature, hacktoberfest-accepted

#70 Footer
  client/components/footer/Footer.js
  client/components/footer/styles.js
  client/pages/_app.js
Labels: feature, hacktoberfest-accepted

#80 Setup/db setup
  Dockerfile
  docker-entrypoint-initdb.d/quiz_db.sql
  package.json
  server/.env.example
Labels: CORE-TEAM, hacktoberfest-accepted

#81 Mobile Menu Dark Redesign
  client/components/header/MobileMenu.js
  client/components/header/styles.js
Labels: Improvement, hacktoberfest-accepted

#78 Contribute page
  client/components/contributepage/HeroSection.js
  client/components/contributepage/InfoSection.js
  client/components/contributepage/ResourcesSection.js
  client/pages/_app.js
  client/pages/contribute.js
Labels: Feature

#94 adding primary keys to subject and tag tables
  package.json
  quiz_db.sql
Labels: Back End

#93 Feature/schema update
  package.json
  quiz_db.sql
Labels: Back End

#95 #27 About Us
  client/components/aboutUs/HeroSection.js
  client/components/aboutUs/InfoSection.js
  client/components/aboutUs/Resources.js
  client/components/aboutUs/styles.js
  client/pages/_app.js
  client/pages/about.js
  client/public/Home.png
Labels: Feature, Front End, hacktoberfest-accepted

#86 Improvement / topic scrollbar and footer
  client/components/header/Header.js
  client/components/quizSelection/styles.js
Labels: Improvement, hacktoberfest-accepted

#92 Organize Header/Footer into Layout
  client/components/footer/styles.js
  client/components/layout/Footer.js
  client/components/layout/Layout.js
  client/components/layout/MobileMenu.js
  client/components/layout/styles.js
  client/pages/_app.js
  client/pages/contribute.js
  client/pages/index.js
  client/pages/quizzes.js
Labels: Improvement, hacktoberfest-accepted

#100 Feature/#74 random quizzes
  server/controllers/apiV1/quiz/getRandomQuizzes.js
  server/controllers/apiV1/quiz/index.js
  server/db/queries/quiz/index.js
  server/db/queries/quiz/select.js
  server/routes/apiV1/quiz.js
Labels: Feature, hacktoberfest-accepted

#99 Feature/add additional quizzes
  quiz_db.sql
  server/quiz_examples/javascript_quiz.json
Labels: Back End, hacktoberfest-accepted

#101 #65 Frontpage "What is Chingu" section
  client/components/frontpage/ChinguSection.js
  client/pages/index.js
  client/public/home-chingu-image.png
  client/public/home-chingu.svg
Labels: Front End, Good First Issue, hacktoberfest-accepted

#91 Documentation update
  CONTRIBUTING.md
  README.md
Labels: Documentation, hacktoberfest-accepted

#103 Feature/#29 light dark toggle
  client/components/contributepage/HeroSection.js
  client/components/contributepage/ResourcesSection.js
  client/components/frontpage/HeroSection.js
  client/components/layout/Layout.js
  client/components/layout/MobileMenu.js
  client/components/layout/styles.js
  client/components/quizSelection/styles.js
  client/components/shared/styles.js
  client/pages/_app.js
Labels: Front End, Improvement, hacktoberfest-accepted

#109 fix dark mode compatibility for what is chingu section
  client/components/frontpage/ChinguSection.js
Labels: Front End, Improvement, hacktoberfest-accepted

#102 Single quiz page and multiple answer selection
  client/components/quizSelection/QuizTile.js
  client/components/quizSingle/AnswerTileContainer.js
  client/components/quizSingle/AnswerTileMark.js
  client/components/quizSingle/AnswerTileText.js
  client/components/quizSingle/NextQuestionBtn.js
  client/components/quizSingle/QuestionHeader.js
  client/components/quizSingle/styles.js
  client/pages/dummy-quiz-data.js
  client/pages/quiz/[slug].js
  client/pages/quizzes.js
Labels: Feature, Front End, hacktoberfest-accepted

#104 Consolodate to one PageHeader component
  client/components/contributepage/HeroSection.js
  client/components/contributepage/InfoSection.js
  client/components/quizSelection/styles.js
  client/components/shared/PageHeader.js
  client/components/shared/styles.js
  client/pages/contribute.js
  client/pages/quizzes.js
Labels: Front End, Improvement

#105 Dockerize front end
  CONTRIBUTING.md
  README.md
  docker-compose.yml
  package.json
Labels: CORE-TEAM, Documentation

#117 hotfix/quiz-page
  client/components/quizSingle/styles.js
  client/pages/quiz/[slug].js
Labels: HOT FIX
