Repository chingu-voyages/moonshot-chingu-quiz, pull requests merged in 2021-02, with the labels that each got.

#138 DB migration in place with TS happy - Much Rejoicing
  client/components/aboutUs/styles.ts
  client/components/quizSelection/QuizTile.tsx
  client/components/quizSelection/TopicSelection.tsx
  client/models/ChinguQuiz/Quiz.ts
  client/models/UI/Quizzes.ts
  client/pages/quiz/[slug].js
  client/pages/quizzes.tsx
  package-lock.json
  package.json
Labels: BUG, CORE-TEAM, Improvement

#141 Feat/quiz result
  components/quizSingle/AnswerTileContainer.tsx
  components/quizSingle/AnswerTileMark.tsx
  components/quizSingle/AnswerTileText.tsx
  components/quizSingle/NextQuestionBtn.tsx
  components/quizSingle/QuestionHeader.tsx
  components/quizSingle/ResultView.tsx
  components/quizSingle/ScoreGraph.tsx
  components/quizSingle/SubmitQuizBtn.tsx
  components/quizSingle/styles.ts
  components/shared/DisplayMessage.tsx
  components/shared/PageHeader.tsx
  components/shared/styles.ts
  models/ChinguQuiz/QuizRecord.ts
  pages/_app.tsx
  pages/quiz/[slug].tsx
  styles/reset.css
  tsconfig.json
Labels: Feature, Front End

#142 Feature/#67 data privacy page
  components/layout/Footer.tsx
  components/layout/styles.ts
  pages/data-privacy.tsx
Labels: Feature, Front End

#145 update texts on home page
  components/frontpage/ChinguSection.tsx
  components/frontpage/HeroSection.tsx
  components/frontpage/InfoSection.tsx
Labels: Improvement

#143 updating next to latest version to support node-fetch 2.6.1
  package-lock.json
  package.json
Labels: HOT FIX
